### ISSUE TITLE
Rewards not showing up?

### ISSUE THREAD

**Issue by timwillhack** [rhomita/twitch-chat-connect#3]
Hello I have integrated your package into my unity 2019.4.10f1 project, upon setting up my authentication and running the example chat scene, messages show up fine, but rewards don't show up at all - I've tried with an external account too thinking maybe it won't show self account posted rewards but neither work.  Any ideas?

**Comment by rhomita** [comment]
> Hello I have integrated your package into my unity 2019.4.10f1 project, upon setting up my authentication and running the example chat scene, messages show up fine, but rewards don't show up at all - I've tried with an external account too thinking maybe it won't show self account posted rewards but neither work. Any ideas?

Only rewards with a message work. Otherwise it won't be detected. Please check it out and let me know!
Also It should work with your own account, you don't need an external account.
