### ISSUE TITLE
Event does not trigger in a ":" input from Chat

### ISSUE THREAD

**Issue by holypunisher** [rhomita/twitch-chat-connect#7]
I installed the code into my unity project and was able to set it up normally and it works normally with normal messages and 

However, if an user were to input ":" into chat, it does not trigger any of the events: onChatMessageReceived, onChatCommandReceived, onChatRewardReceived 

Weird behaviour happens when emotes like :D and :| is used. For example, viewer types ":) :|" in chat, it only shows the "|" in the chatMessage.Message parameter

so longer sentences like "Welcome to the stream :)" the chatMessage.Message only contains ")"

**Comment by rhomita** [comment]
@holypunisher We've fixed the problem in the new version (1.5.0). I already published it, it could take 24-48 hours to be available in the asset store.
